# Create inst/default.nix
on:
  push:
    branches: [main, master]

name: create_inst_default.nix

permissions:
  contents: read, write

jobs:
  devtools:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build default.nix with 2 local packages
        run: |
          nix-shell ./inst/extdata/default.nix --run "Rscript -e \"library(rix);latest_commit <- tryCatch(expr = {sys::as_text(sys::exec_internal('git', c('rev-parse', 'master'))$stdout)}, error = function(e) '4d96207e7f69cbadca5349e9caa5bcc4059c1dc3');rix('4.3.1', git_pkgs = list(package_name = 'rix', repo_url = 'https://github.com/b-rodrigues/rix/', branch_name = 'master', commit = latest_commit), ide = 'other', project_path = ./inst/extdata, overwrite = TRUE)\""

      - name: Commit and push default.nix
        run: |
          git config --global user.name 'CI Bot'
          git config --global user.email 'ci-bot@users.noreply.github.com'
          git add ./inst/extdata/default.nix
          git commit -m "Updated default.nix"
          git push origin master