on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: nix-builder for inst/extdata/default.nix

permissions:
  contents: read

jobs:
  run-x86_64-linux:
    name: nix builder for Ubuntu
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Run `nix-build ./inst/extdata/default.nix`
      run: |
        nix-build ./inst/extdata/default.nix
        nix-shell ./inst/extdata/default.nix

  run-x86_64-darwin:
    name: nix builder for MacOS X86_64
    # the DeterminateSystems action currently uses macos-12
    # https://github.com/DeterminateSystems/nix-installer-action/blob/main/.github/workflows/ci.yml
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Run `nix-build ./inst/extdata/default.nix`
      run: |
        nix-build ./inst/extdata/default.nix
        nix-shell ./inst/extdata/default.nix
