# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main-not, master-not]
  pull_request:
    branches: [main-not, master-not]

name: tests-r-via-system

permissions:
  contents: read

jobs:
  devtools:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools, any::codetools any::covr

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: devtools::test() via system R
        run: Rscript -e 'devtools::test()'
        
      # - name: covr::codecov() via system R
      #   run: Rscript -e 'covr::codecov(quiet = FALSE, clean = TRUE, install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package"))'

      - name: Show testthat output
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
